### ISSUE TITLE
Fails to enable

### ISSUE THREAD

**Issue by klinkeye** [hurenkam/node-red-contrib-mh-hue#1]
Hi, upon installing node-red-hue-services v0.5.7 for Node-Red v14.0.0

[@hurenkam/node-red-hue-services/all] Error: BridgeConfigNode already registered (line:39)
Attempted to remove and re-install but same issue

Under User Settings > Palette > Nodes it lists "0 nodes"

**Comment by hurenkam** [comment]
This would seem to be a namespace conflict between this palette and another palette that is installed in your system.
Perhaps you can elaborate a bit more on your node-red setup, what node-red version are you using (i presume 14.0.0 is the nodejs version), and what other node-red palettes are installed?

**Comment by hurenkam** [comment]
This issue should be fixed now with version 0.6.0
Note however, that all node type names have changed because of this, so any existing flows will not work with the newer version unless you manually change the node names in flows.json
All node names are now prefixed with "@hurenkam/hue-services/".
